export { default as SplashPage }    from './SplashPage'
export { default as AuthPage }      from './AuthPage'
export { default as HomePage }      from './HomePage'
export { default as StorePage }     from './StorePage'
export { default as CartPage }      from './CartPage'
export { default as CheckoutPage }  from './CheckoutPage'
export { default as TrackingPage }  from './TrackingPage'
export { default as OrdersPage }    from './OrdersPage'
export { ProfilePage }              from './OtherPages'
export { FavoritesPage }            from './OtherPages'
